{{- if .Values.ingress.enabled }}
{{- $fullname := include "ghost-on-kubernetes.fullname" . }}
{{- $tls := .Values.ingress.tls }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullname }}-ingress
  labels:
    {{- include "ghost-on-kubernetes.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingress
  annotations:
    {{- if eq .Values.ingress.preset "nginx" }}
    kubernetes.io/ingress.class: {{ .Values.ingress.className | default "nginx" | quote }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{- end }}
    {{- if eq .Values.ingress.preset "traefik" }}
    traefik.ingress.kubernetes.io/router.entrypoints: {{ .Values.ingress.entrypoint | default "websecure" | quote }}
    {{- end }}
    {{- if and $tls.enabled (or (eq $tls.mode "certManager") (eq $tls.mode "both")) }}
    cert-manager.io/{{ $tls.certManager.issuerKind | lower }}: {{ $tls.certManager.issuer | quote }}
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . | quote }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host | quote }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path | default "/" | quote }}
        pathType: {{ .pathType | default "ImplementationSpecific" | quote }}
        backend:
          service:
            name: {{ $fullname }}-service
            port:
              name: ghk8s
      {{- end }}
  {{- end }}
  {{- if $tls.enabled }}
  tls:
  - hosts:
    {{- range $tls.hosts }}
    - {{ . | quote }}
    {{- end }}
    {{- if or (eq $tls.mode "manual") (eq $tls.mode "both") }}
    secretName: {{ $tls.secretName }}
    {{- else if eq $tls.mode "certManager" }}
    secretName: {{ $fullname }}-tls-cert
    {{- end }}
  {{- end }}
{{- end }}
