{{- if .Values.persistence.ghost.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ghost-on-kubernetes.fullname" . }}-content
  labels:
    {{- include "ghost-on-kubernetes.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.persistence.ghost.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.persistence.ghost.accessMode | quote }}
  {{- with .Values.persistence.ghost.selector }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  resources:
    requests:
      storage: {{ required "persistence.ghost.size is required when persistence.ghost.enabled is true" .Values.persistence.ghost.size | quote }}
{{- end }}
{{- if and .Values.mysql.enabled .Values.persistence.mysql.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ghost-on-kubernetes.fullname" . }}-mysql-pvc
  labels:
    {{- include "ghost-on-kubernetes.labels" . | nindent 4 }}
    app.kubernetes.io/component: database-storage
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.persistence.mysql.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.persistence.mysql.accessMode | quote }}
  {{- with .Values.persistence.mysql.selector }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  resources:
    requests:
      storage: {{ required "persistence.mysql.size is required when mysql.enabled and persistence.mysql.enabled are true" .Values.persistence.mysql.size | quote }}
{{- end }}
{{- if and .Values.valkey.enabled .Values.persistence.valkey.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ghost-on-kubernetes.fullname" . }}-valkey-pvc
  labels:
    {{- include "ghost-on-kubernetes.labels" . | nindent 4 }}
    app.kubernetes.io/component: cache-storage
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.persistence.valkey.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.persistence.valkey.accessMode | quote }}
  {{- with .Values.persistence.valkey.selector }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  resources:
    requests:
      storage: {{ required "persistence.valkey.size is required when valkey.enabled and persistence.valkey.enabled are true" .Values.persistence.valkey.size | quote }}
{{- end }}
