{{- if and .Values.valkey.enabled .Values.valkey.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ghost-on-kubernetes.fullname" . }}-valkey
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "ghost-on-kubernetes.name" . }}-valkey
    {{- include "ghost-on-kubernetes.labels" . | nindent 4 }}
    app.kubernetes.io/component: cache-secret
type: Opaque
stringData:
  valkey-password: {{ .Values.valkey.auth.password | quote }}
{{- end }}
