{{- if and .Values.mysql.enabled (not .Values.mysql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ghost-on-kubernetes.mysql.secretName" . }}
  labels:
    {{- include "ghost-on-kubernetes.labels" . | nindent 4 }}
    app.kubernetes.io/component: database-secret
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  MYSQL_DATABASE: {{ required "mysql.auth.database is required" .Values.mysql.auth.database | quote }}
  MYSQL_USER: {{ required "mysql.auth.username is required" .Values.mysql.auth.username | quote }}
  MYSQL_PASSWORD: {{ required "mysql.auth.password is required, or set mysql.auth.existingSecret" .Values.mysql.auth.password | quote }}
  MYSQL_ROOT_PASSWORD: {{ required "mysql.auth.rootPassword is required, or set mysql.auth.existingSecret" .Values.mysql.auth.rootPassword | quote }}
  MYSQL_HOST: '%'
{{- end }}
