{{- if and .Values.ingress.enabled .Values.ingress.tls.enabled (or (eq .Values.ingress.tls.mode "manual") (eq .Values.ingress.tls.mode "both")) }}
{{- if and .Values.ingress.tls.certificate .Values.ingress.tls.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.tls.secretName | quote }}
  labels:
    {{- include "ghost-on-kubernetes.labels" . | nindent 4 }}
    app.kubernetes.io/component: tls-secret
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: kubernetes.io/tls
stringData:
  tls.crt: {{ .Values.ingress.tls.certificate | quote }}
  tls.key: {{ .Values.ingress.tls.key | quote }}
{{- end }}
{{- end }}
