{{- if .Values.mysql.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ghost-on-kubernetes.fullname" . }}-mysql
  labels:
    {{- include "ghost-on-kubernetes.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  serviceName: {{ include "ghost-on-kubernetes.fullname" . }}-mysql-service
  replicas: {{ .Values.mysql.replicaCount }}
  selector:
    matchLabels:
      {{- include "ghost-on-kubernetes.mysql.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ghost-on-kubernetes.mysql.selectorLabels" . | nindent 8 }}
      {{- with .Values.mysql.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range . }}
      - name: {{ .name | quote }}
      {{- end }}
      {{- end }}
      serviceAccountName: {{ include "ghost-on-kubernetes.serviceAccountName" . }}
      {{- if .Values.mysql.initContainer.enabled }}
      initContainers:
      - name: mysql-init
        securityContext:
          {{- toYaml .Values.initContainer.securityContext | nindent 10 }}
        image: "{{ .Values.initContainer.image.repository }}:{{ .Values.initContainer.image.tag }}"
        imagePullPolicy: {{ .Values.initContainer.image.pullPolicy | quote }}
        command:
        - /bin/sh
        - -c
        - |
          set -e
          echo 'Changing ownership of mysql mount directory to 65532:65532'
          chown -Rfv 65532:65532 /mnt/mysql || echo 'Error changing ownership of mysql mount directory to 65532:65532'
          echo 'Changing ownership of tmp mount directory to 65532:65532'
          chown -Rfv 65532:65532 /mnt/tmp || echo 'Error changing ownership of tmp mount directory to 65532:65532'
          echo 'Changing ownership of socket mount directory to 65532:65532'
          chown -Rfv 65532:65532 /mnt/var/run/mysqld || echo 'Error changing ownership of socket mount directory to 65532:65532'
        volumeMounts:
        - name: mysql-volume
          mountPath: /mnt/mysql
          subPath: mysql-empty-subdir
          readOnly: false
        - name: mysql-tmp
          mountPath: /mnt/tmp
          readOnly: false
        - name: mysql-socket
          mountPath: /mnt/var/run/mysqld
          readOnly: false
        resources:
          {{- toYaml .Values.mysql.initResources | nindent 10 }}
      {{- end }}
      containers:
      - name: mysql
        securityContext:
          {{- toYaml .Values.mysql.securityContext | nindent 10 }}
        image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
        imagePullPolicy: {{ .Values.mysql.image.pullPolicy | quote }}
        envFrom:
        - secretRef:
            name: {{ include "ghost-on-kubernetes.mysql.secretName" . }}
        resources:
          {{- toYaml .Values.mysql.resources | nindent 10 }}
        ports:
        - containerPort: {{ .Values.mysql.containerPort }}
          protocol: TCP
          name: mysqlgh
        {{- with .Values.mysql.livenessProbe.enabled }}
        livenessProbe:
          tcpSocket:
            port: mysqlgh
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 6
        {{- end }}
        {{- with .Values.mysql.readinessProbe.enabled }}
        readinessProbe:
          tcpSocket:
            port: mysqlgh
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        {{- end }}
        volumeMounts:
        - name: mysql-volume
          mountPath: /var/lib/mysql
          subPath: mysql-empty-subdir
          readOnly: false
        - name: mysql-tmp
          mountPath: /tmp
          readOnly: false
        - name: mysql-socket
          mountPath: /var/run/mysqld
          readOnly: false
      automountServiceAccountToken: false
      {{- with (include "ghost-on-kubernetes.affinity" .Values.mysql.affinity | fromYaml) }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mysql.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mysql.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mysql.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mysql.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: mysql-volume
        {{- if .Values.persistence.mysql.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "ghost-on-kubernetes.fullname" . }}-mysql-pvc
        {{- else }}
        emptyDir:
          sizeLimit: {{ .Values.volumes.mysqlData.sizeLimit | quote }}
        {{- end }}
      - name: mysql-tmp
        emptyDir:
          sizeLimit: {{ .Values.volumes.mysqlTmp.sizeLimit | quote }}
      - name: mysql-socket
        emptyDir:
          sizeLimit: {{ .Values.volumes.mysqlSocket.sizeLimit | quote }}
          {{- end }}
