apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: ghost-on-kubernetes
  labels:
    app: ghost-on-kubernetes
    app.kubernetes.io/name: tls-secret
    app.kubernetes.io/instance: ghost-on-kubernetes
    app.kubernetes.io/version: '5.92'
    app.kubernetes.io/component: tls-secret
    app.kubernetes.io/part-of: ghost-on-kubernetes
    

type: kubernetes.io/tls
stringData:
  tls.crt: content-tls-crt-base64 # Optional, if you want to use your own TLS certificate
  tls.key: content-tls-key-base64 # Optional, if you want to use your own TLS certificate
