# Point the Ghost probes at the development hostname.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-on-kubernetes
  namespace: ghost-on-kubernetes
spec:
  template:
    spec:
      containers:
        - name: ghost-on-kubernetes
          readinessProbe:
            httpGet:
              httpHeaders:
                - name: X-Forwarded-Proto
                  value: http
                - name: Host
                  value: ghost.localhost
          livenessProbe:
            httpGet:
              httpHeaders:
                - name: X-Forwarded-Proto
                  value: http
                - name: Host
                  value: ghost.localhost
