apiVersion: v1
kind: Secret
metadata:
  name: ghost-config-prod
  namespace: ghost-k8s
type: Opaque
stringData:
  config.development.json: |-
    {
      "url": "http://localhost:2368",
      "admin": {
        "url": "http://localhost:2368"
      },
      "server": {
        "port": 2368,
        "host": "0.0.0.0"
      },
      "mail": {
        "transport": "direct"
      },
      "logging": {
        "transports": [
          "stdout"
        ]
      },
      "database": {
        "client": "sqlite3",
        "connection": {
          "filename": "/var/lib/ghost/content/data/ghost.db"
        }
      },
      "debug": true,
      "process": "local",
      "paths": {
        "contentPath": "/var/lib/ghost/content"
      }
    }
    