name: ARM Test build

on:
  workflow_dispatch:


permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit
      -
        name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1
          
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0
        with:
          driver-opts: |
            network=host

      - name: Gets GHOST_VERSION
        continue-on-error: false
        id: versions
        run: |
          echo "GHOST_VERSION=$(curl -s https://api.github.com/repos/tryghost/ghost/releases/latest | jq '.name' | sed 's/\"//g')" >> $GITHUB_OUTPUT
          

      - name: Show GHOST_VERSION
        continue-on-error: true
        run: echo ${{ steps.versions.outputs.GHOST_VERSION }} 
      -
        name: Build
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        id: build-pr
        with:
          context: .
          platforms: linux/arm64
          cache-from: type=gha,mode=max
          cache-to: type=gha,mode=max
          push: false
          build-args: GHOST_VERSION=${{ steps.versions.outputs.GHOST_VERSION }}
          
